#commenting
disqus: true
disqus_page: blog-gregormeyenberg-de.disqus.com
disqus_dev_mode: true #set to false or remove for production

#tracking
google_analytics: UA-83804940-1
        
# Static files
js: js
css: css

# Theme version
version: 0.0.1
